{
	"coordinateVisible":true,
	"createAt":"2017-11-15 10:17:20",
	"defaultRegionCode":"320000",
	"description":"This is the first template.",
	"dockWidgets":[
		{
			"config":{
				"expandLevel":1
			},
			"desc":"分类数据",
			"display":true,
			"icon":"glyphicon glyphicon-tasks",
			"id":"DataList",
			"label":"数据",
			"open":false,
			"url":"DataList",
			"weight":0
		},
		{
			"config":{
				"autoCreateProject":false,
				"exportXls":false,
				"identifyLayers":[],
				"modifyProVideo":false,
				"newProjectLayer":[],
				"panoramaSwitch":"off",
				"popupStyle":"layer",
				"proType":[
					{
						"color":"#ffb61e",
						"name":"建设用地"
					},
					{
						"color":"#00bc12",
						"name":"农用地"
					},
					{
						"color":"#ff2d51",
						"name":"未利用地"
					},
					{
						"color":"#000000",
						"name":"其他"
					}
				],
				"searchVideoByXy":false,
				"showArcCenter":false,
				"showStatus":false,
				"style":"list",
				"supervise":false,
				"txVersionEnable":false,
				"txtSymbol":{
					"color":"#32bfef",
					"fontSize":"12"
				}
			},
			"desc":"视频管理",
			"display":true,
			"icon":"glyphicon glyphicon-facetime-video",
			"id":"VideoManager",
			"label":"视频",
			"open":false,
			"url":"VideoManager",
			"weight":0
		}
	],
	"geometryService":{
		"url":"http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer"
	},
	"logo":"/omp/file/logo/维尼logo",
	"logoVisible":true,
	"map":{
		"baseLayers":[],
		"defaultScale":0,
		"initExtent":{
			"spatialReference":{
				"wkt":"PROJCS[\"Xian_1980_3_Degree_GK_CM_120E\",GEOGCS[\"GCS_Xian_1980\",DATUM[\"D_Xian_1980\",SPHEROID[\"Xian_1980\",6378140.0,298.257]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Gauss_Kruger\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",119.0],PARAMETER[\"Scale_Factor\",1.0],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"
			},
			"xmax":516132.60124840005,
			"xmin":496289.4513229,
			"ymax":3727521.851378075,
			"ymin":3714719.819168075
		},
		"operationalLayers":[
			{
				"alias":"房屋",
				"alpha":1,
				"category":"1",
				"group":"015fbd38090c4028b2ff5fbd1f8d0019",
				"id":"015fbd6fa3b54028b2ff5fbd5f530002",
				"index":1,
				"name":"FW",
				"type":"dynamic",
				"url":"/oms/arcgisrest/1/FW/MapServer",
				"visible":true,
				"xMaxExtent":511494.552,
				"xMinExtent":497055.873,
				"xzdm":"320000",
				"yMaxExtent":3721757.416,
				"yMinExtent":3717380.672,
				"year":2017
			},
			{
				"alias":"地籍图",
				"alpha":1,
				"category":"1",
				"group":"015fbd38090c4028b2ff5fbd1f8d0019",
				"id":"015fbd2252834028b2ff5fbd1f8d0002",
				"index":2,
				"name":"DJZQ",
				"type":"dynamic",
				"url":"/oms/arcgisrest/1/DJZQ/MapServer",
				"visible":false,
				"xMaxExtent":515038.609405,
				"xMinExtent":496999.3822,
				"xzdm":"320000",
				"yMaxExtent":3723516.639442,
				"yMinExtent":3717252.7974,
				"year":2011
			},
			{
				"alias":"宗地",
				"alpha":1,
				"category":"1",
				"group":"015fbd38090c4028b2ff5fbd1f8d0019",
				"id":"0160056371c04028b2ff600537e70008",
				"index":3,
				"name":"ZD",
				"type":"dynamic",
				"url":"/oms/arcgisrest/1/ZD/MapServer",
				"visible":true,
				"xMaxExtent":511504.9092,
				"xMinExtent":497125.683,
				"xzdm":"320000",
				"yMaxExtent":3721911.411316,
				"yMinExtent":3717335.088,
				"year":2017
			}
		]
	},
	"name":"test_1115",
	"title":"江苏省国土资源 一张图",
	"widgetContainer":{
		"widgets":[
			{
				"config":{
					"importDatabaseScLpbAddress":"/estateplat-cadastre/static/html/ImportDatabaseLpb/ImportDatabaseScLpb.html",
					"importDatabaseYcLpbAddress":"/estateplat-cadastre/static/html/ImportDatabaseLpb/ImportDatabaseYcLpb.html",
					"interfaceHost":"http://192.168.50.14:8080",
					"layers":[
						{
							"html":"",
							"layerIndex":"0",
							"layerName":"房屋",
							"layerUrl":"/oms/arcgisrest/HA/FW/MapServer/0",
							"link":{
								"tip":"",
								"url":""
							},
							"queryFields":{
								"fields":[
									{
										"alias":"隶属宗地",
										"name":"LSZD",
										"operator":"like",
										"type":"STRING"
									},
									{
										"alias":"自然幢号",
										"name":"ZRZH",
										"operator":"like",
										"type":"STRING"
									}
								],
								"prefix":"%"
							},
							"returnFields":[
								{
									"alias":"座落地址",
									"name":"ZLDZ",
									"type":"STRING"
								},
								{
									"alias":"隶属宗地",
									"name":"LSZD",
									"type":"STRING"
								},
								{
									"alias":"自然幢号",
									"name":"ZRZH",
									"type":"STRING"
								},
								{
									"alias":"OBJECTID",
									"name":"OBJECTID",
									"type":"STRING"
								}
							],
							"serviceId":"015de3dbd93f4028b2425de38ad30165",
							"titleField":{
								"alias":"房屋名称",
								"name":"FWMC"
							},
							"type":"field"
						},
						{
							"html":"",
							"layerIndex":"0",
							"layerName":"宗地",
							"layerUrl":"/oms/arcgisrest/HA/ZD/MapServer/0",
							"link":{
								"tip":"",
								"url":""
							},
							"queryFields":{
								"fields":[{
									"alias":"地籍号",
									"name":"DJH",
									"operator":"like",
									"type":"STRING"
								}],
								"prefix":"%"
							},
							"returnFields":[
								{
									"alias":"土地座落",
									"name":"TDZL",
									"type":"STRING"
								},
								{
									"alias":"地籍号",
									"name":"DJH",
									"type":"STRING"
								}
							],
							"serviceId":"015de3dbfffc4028b2425de38ad30189",
							"titleField":{
								"alias":"地籍号",
								"name":"DJH"
							},
							"type":"field"
						}
					],
					"merge":false
				},
				"display":false,
				"id":"f160a03bf3e84028b2ff60a03bf30001",
				"label":"导入房产数据库楼盘表",
				"open":false,
				"url":"ImportDatabaseLpb",
				"weight":0
			},
			{
				"config":{
					"addItemAddress":"estateplat-cadastre/static/html/FWDZGL/addItem.html",
					"editItemAddress":"estateplat-cadastre/static/html/FWDZGL/editItem.html",
					"interfaceHost":"http://192.168.50.14:8080/"
				},
				"display":false,
				"id":"f16044a843bf4028b2ff6044a8430001",
				"label":"房屋独幢管理",
				"open":false,
				"url":"FWDZGL",
				"weight":2
			},
			{
				"config":{
					"addItemAddress":"estateplat-cadastre/static/html/XMDZGL/addItem.html",
					"editItemAddress":"estateplat-cadastre/static/html/XMDZGL/editItem.html",
					"interfaceHost":"http://192.168.50.14:8080/"
				},
				"display":true,
				"id":"f15ffb7c47ea4028b2ff5ffb7c470001",
				"label":"项目多幢管理",
				"open":false,
				"url":"XMDZGL",
				"weight":3
			}
		],
		"widgetsGroup":[{
			"icon":"",
			"id":"3F131C37-EDB4-476C-845D-8BBB592AD815",
			"label":"多项与独幢",
			"type":0,
			"url":"",
			"weight":2,
			"widgets":[
				{
					"display":true,
					"id":"f15ffb7c47ea4028b2ff5ffb7c470001",
					"label":"项目多幢管理",
					"open":false,
					"url":"XMDZGL",
					"weight":3
				},
				{
					"display":false,
					"id":"f16044a843bf4028b2ff6044a8430001",
					"label":"房屋独幢管理",
					"open":false,
					"url":"FWDZGL",
					"weight":2
				}
			]
		}]
	},
	"widgets":[
		{
			"config":{
				"style":"normal"
			},
			"display":true,
			"id":"MenuBar",
			"open":false,
			"url":"MenuBar",
			"weight":0
		},
		{
			"display":true,
			"id":"Navigation",
			"open":false,
			"url":"Navigation",
			"weight":0
		},
		{
			"config":{
				"style":"default"
			},
			"display":true,
			"open":true,
			"url":"Scalebar",
			"weight":0
		},
		{
			"display":true,
			"id":"Region",
			"open":false,
			"url":"Region",
			"weight":0
		},
		{
			"config":{
				"layers":[]
			},
			"display":false,
			"icon":"fa-location",
			"id":"Location",
			"label":"定位",
			"open":false,
			"url":"Location",
			"weight":0
		}
	]
}