{
	"coordinateVisible":true,
	"createAt":"2017-09-12 09:52:32",
	"defaultRegionCode":"320802",
	"description":"",
	"dockWidgets":[
		{
			"config":{
				"expandLevel":1
			},
			"desc":"分类数据",
			"display":true,
			"icon":"glyphicon glyphicon-tasks",
			"id":"DataList",
			"label":"数据",
			"open":false,
			"url":"DataList",
			"weight":0
		},
		{
			"config":{
				"autoCreateProject":false,
				"exportXls":false,
				"identifyLayers":[],
				"modifyProVideo":false,
				"newProjectLayer":[],
				"panoramaSwitch":"off",
				"popupStyle":"layer",
				"proType":[
					{
						"color":"#ffb61e",
						"name":"建设用地"
					},
					{
						"color":"#00bc12",
						"name":"农用地"
					},
					{
						"color":"#ff2d51",
						"name":"未利用地"
					},
					{
						"color":"#000000",
						"name":"其他"
					}
				],
				"searchVideoByXy":false,
				"showArcCenter":false,
				"showStatus":false,
				"style":"list",
				"supervise":false,
				"txVersionEnable":false,
				"txtSymbol":{
					"color":"#32bfef",
					"fontSize":"12"
				}
			},
			"desc":"视频管理",
			"display":true,
			"icon":"glyphicon glyphicon-facetime-video",
			"id":"VideoManager",
			"label":"视频",
			"open":false,
			"url":"VideoManager",
			"weight":0
		}
	],
	"geometryService":{
		"url":"http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer"
	},
	"logo":"/omp/file/logo/test",
	"logoVisible":false,
	"map":{
		"baseLayers":[],
		"defaultScale":0,
		"initExtent":{
			"spatialReference":{
				"wkt":"PROJCS[\"Xian_1980_3_Degree_GK_CM_120E\",GEOGCS[\"GCS_Xian_1980\",DATUM[\"D_Xian_1980\",SPHEROID[\"Xian_1980\",6378140.0,298.257]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Gauss_Kruger\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",119.0],PARAMETER[\"Scale_Factor\",1.0],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"
			},
			"xmax":515940.57076525,
			"xmin":496097.42083975,
			"ymax":3726785.734526,
			"ymin":3713983.702316
		},
		"operationalLayers":[
			{
				"alias":"地籍子区图层",
				"alpha":1,
				"category":"HA",
				"group":"015de3ca1b944028b2425de38ad30134",
				"id":"015de3dbb9414028b2425de38ad3014e",
				"index":1,
				"name":"DJZQ",
				"type":"dynamic",
				"url":"/oms/arcgisrest/HA/DJZQ/MapServer",
				"visible":true,
				"xMaxExtent":515038.609405,
				"xMinExtent":496999.3822,
				"xzdm":"320802",
				"yMaxExtent":3723516.639442,
				"yMinExtent":3717252.7974,
				"year":2017
			},
			{
				"alias":"宗海图层",
				"alpha":1,
				"category":"HA",
				"group":"015de3ca1b944028b2425de38ad30134",
				"id":"015de3dc220b4028b2425de38ad301c5",
				"index":2,
				"name":"ZH",
				"type":"dynamic",
				"url":"/oms/arcgisrest/HA/ZH/MapServer",
				"visible":true,
				"xMaxExtent":499670.556939,
				"xMinExtent":499312.513,
				"xzdm":"320802",
				"yMaxExtent":3721522.407001,
				"yMinExtent":3721031.988492,
				"year":2017
			},
			{
				"alias":"宗地图层",
				"alpha":1,
				"category":"HA",
				"group":"015de3ca1b944028b2425de38ad30134",
				"id":"015de3dbfffc4028b2425de38ad30189",
				"index":3,
				"name":"ZD",
				"type":"dynamic",
				"url":"/oms/arcgisrest/HA/ZD/MapServer",
				"visible":true,
				"xMaxExtent":511504.9092,
				"xMinExtent":497125.683,
				"xzdm":"320802",
				"yMaxExtent":3721911.411316,
				"yMinExtent":3717335.088,
				"year":2017
			},
			{
				"alias":"房屋图层",
				"alpha":1,
				"category":"HA",
				"group":"015de3ca1b944028b2425de38ad30134",
				"id":"015de3dbd93f4028b2425de38ad30165",
				"index":4,
				"name":"FW",
				"type":"dynamic",
				"url":"/oms/arcgisrest/HA/FW/MapServer",
				"visible":true,
				"xMaxExtent":511494.552,
				"xMinExtent":497055.873,
				"xzdm":"320802",
				"yMaxExtent":3721757.416,
				"yMinExtent":3717380.672,
				"year":2017
			}
		]
	},
	"name":"web落宗模板",
	"title":"江苏省国土资源 一张图",
	"widgetContainer":{
		"widgets":[],
		"widgetsGroup":[
			{
				"icon":"",
				"id":"4075D9EC-914C-4280-94C7-51771FB765BA",
				"label":"落宗功能",
				"type":0,
				"url":"",
				"weight":1,
				"widgets":[
					{
						"config":{
							"BDCDYCXDetialInterface":"/estateplat-cadastre/bdcdyXx",
							"BDCDYCXInterface":"/estateplat-cadastre/bdcdy/queryBdcdyJson",
							"BDCLXInterface":"/estateplat-cadastre/bdcdy/initBdclx",
							"CXLXInterface":"/estateplat-cadastre/bdcdy/getCxlxByBdclx",
							"XZQFWInterface":"/estateplat-cadastre/bdcdy/getXzqdm",
							"interfaceHost":"http://192.168.50.107:8888",
							"queryLayer":{
								"html":"",
								"layerIndex":"0",
								"layerName":"宗地",
								"layerUrl":"/oms/arcgisrest/HA/ZD/MapServer/0",
								"queryField":{
									"alias":"地籍号",
									"name":"DJH",
									"operator":"like",
									"prefix":"%",
									"type":"STRING"
								},
								"serviceId":"015e2d149adb4028824e5e2cc55300b8"
							},
							"zhQueryLayer":{
								"html":"",
								"layerIndex":"0",
								"layerName":"宗海",
								"layerUrl":"oms/arcgisrest/HA/ZH/MapServer/0",
								"queryField":{
									"alias":"宗海代码",
									"name":"ZHDM",
									"operator":"like",
									"prefix":"%",
									"type":"STRING"
								},
								"serviceId":"015e2d149adb4028824e5e2cc55300b8"
							}
						},
						"display":false,
						"group":"4075D9EC-914C-4280-94C7-51771FB765BA",
						"id":"f15dc49e0aa84028b2425dc49e0a0001",
						"label":"不动产单元查询",
						"open":false,
						"url":"不动产单元查询",
						"weight":1
					},
					{
						"config":{
							"bdchycxAddress":"/estateplat-cadastre/static/html/BDCHYCX/index.html",
							"interfaceHost":"http://192.168.50.107:8888",
							"withoutUi":true
						},
						"display":false,
						"group":"4075D9EC-914C-4280-94C7-51771FB765BA",
						"id":"2FE0742B-C631-4AA1-AE73-3077BFB59B84",
						"label":"不动产海域查询",
						"open":false,
						"url":"BDCHYCX",
						"weight":2
					},
					{
						"config":{
							"importScLpbAddress":"/estateplat-cadastre/static/html/ImportScLpb/ImportScLpb.html",
							"interfaceHost":"http://192.168.50.127:8080",
							"layers":[
								{
									"html":"",
									"layerIndex":"0",
									"layerName":"房屋",
									"layerUrl":"/oms/arcgisrest/HA/FW/MapServer/0",
									"link":{
										"tip":"",
										"url":""
									},
									"queryFields":{
										"fields":[
											{
												"alias":"隶属宗地",
												"name":"LSZD",
												"operator":"like",
												"type":"STRING"
											},
											{
												"alias":"自然幢号",
												"name":"ZRZH",
												"operator":"like",
												"type":"STRING"
											}
										],
										"prefix":"%"
									},
									"returnFields":[
										{
											"alias":"座落地址",
											"name":"ZLDZ",
											"type":"STRING"
										},
										{
											"alias":"隶属宗地",
											"name":"LSZD",
											"type":"STRING"
										}
									],
									"serviceId":"015de3dbd93f4028b2425de38ad30165",
									"titleField":{
										"alias":"房屋名称",
										"name":"FWMC"
									},
									"type":"field"
								},
								{
									"html":"",
									"layerIndex":"0",
									"layerName":"宗地",
									"layerUrl":"/oms/arcgisrest/HA/ZD/MapServer/0",
									"link":{
										"tip":"",
										"url":""
									},
									"queryFields":{
										"fields":[{
											"alias":"地籍号",
											"name":"DJH",
											"operator":"like",
											"type":"STRING"
										}],
										"prefix":"%"
									},
									"returnFields":[
										{
											"alias":"土地座落",
											"name":"TDZL",
											"type":"STRING"
										},
										{
											"alias":"地籍号",
											"name":"DJH",
											"type":"STRING"
										}
									],
									"serviceId":"015de3dbfffc4028b2425de38ad30189",
									"titleField":{
										"alias":"地籍号",
										"name":"DJH"
									},
									"type":"field"
								}
							],
							"merge":false
						},
						"display":false,
						"group":"4075D9EC-914C-4280-94C7-51771FB765BA",
						"id":"287A4CF5-A640-4AF3-8219-72EA290F6AA3",
						"label":"实测楼盘表导入",
						"open":false,
						"url":"ImportScLpb",
						"weight":3
					},
					{
						"config":{
							"corrlateLpbAddress":"/estateplat-cadastre/static/html/CorrlateLpb/RelatedBuildingTable.html",
							"interfaceHost":"http://192.168.50.127:8080",
							"layers":[
								{
									"html":"",
									"layerIndex":"0",
									"layerName":"房屋",
									"layerUrl":"/oms/arcgisrest/HA/FW/MapServer/0",
									"link":{
										"tip":"",
										"url":""
									},
									"queryFields":{
										"fields":[
											{
												"alias":"隶属宗地",
												"name":"LSZD",
												"operator":"like",
												"type":"STRING"
											},
											{
												"alias":"自然幢号",
												"name":"ZRZH",
												"operator":"like",
												"type":"STRING"
											}
										],
										"prefix":"%"
									},
									"returnFields":[
										{
											"alias":"座落地址",
											"name":"ZLDZ",
											"type":"STRING"
										},
										{
											"alias":"隶属宗地",
											"name":"LSZD",
											"type":"STRING"
										}
									],
									"serviceId":"015de3dbd93f4028b2425de38ad30165",
									"titleField":{
										"alias":"房屋名称",
										"name":"FWMC"
									},
									"type":"field"
								},
								{
									"html":"",
									"layerIndex":"0",
									"layerName":"宗地",
									"layerUrl":"/oms/arcgisrest/HA/ZD/MapServer/0",
									"link":{
										"tip":"",
										"url":""
									},
									"queryFields":{
										"fields":[{
											"alias":"地籍号",
											"name":"DJH",
											"operator":"like",
											"type":"STRING"
										}],
										"prefix":"%"
									},
									"returnFields":[
										{
											"alias":"土地座落",
											"name":"TDZL",
											"type":"STRING"
										},
										{
											"alias":"地籍号",
											"name":"DJH",
											"type":"STRING"
										}
									],
									"serviceId":"015de3dbfffc4028b2425de38ad30189",
									"titleField":{
										"alias":"地籍号",
										"name":"DJH"
									},
									"type":"field"
								}
							],
							"merge":false
						},
						"display":false,
						"group":"4075D9EC-914C-4280-94C7-51771FB765BA",
						"id":"7E45AFCC-4292-4305-9B08-603789CE4736",
						"label":"关联楼盘表",
						"open":false,
						"url":"RelatedBuildingTable",
						"weight":4
					}
				]
			},
			{
				"icon":"",
				"id":"364A0361-2801-4DFE-A125-95E46E93D240",
				"label":"地图功能",
				"type":0,
				"url":"",
				"weight":6,
				"widgets":[
					{
						"config":{
							"layers":[
								{
									"enableVideo":false,
									"html":"",
									"layerIndex":"0",
									"layerName":"地籍子区",
									"link":{
										"defaultOpen":false,
										"tip":"",
										"url":""
									},
									"returnFields":[{
										"alias":"地籍子区编号",
										"name":"DJZQBH",
										"type":"STRING"
									}],
									"serviceId":"015de3dbb9414028b2425de38ad3014e",
									"titleField":{
										"alias":"地籍子区名称",
										"name":"DJZQMC"
									},
									"type":"field"
								},
								{
									"enableVideo":false,
									"html":"",
									"layerIndex":"0",
									"layerName":"宗地",
									"link":{
										"defaultOpen":false,
										"tip":"",
										"url":""
									},
									"returnFields":[{
										"alias":"不动产单元号",
										"name":"BDCDYH",
										"type":"STRING"
									}],
									"serviceId":"015de3dbfffc4028b2425de38ad30189",
									"titleField":{
										"alias":"地籍号",
										"name":"DJH"
									},
									"type":"field"
								}
							]
						},
						"display":false,
						"group":"364A0361-2801-4DFE-A125-95E46E93D240",
						"icon":"/omp/img/menu/identify.png",
						"id":"AB6AC409-33E0-45BC-A767-FE5AFB2A4771",
						"label":"属性识别",
						"open":false,
						"url":"Identify",
						"weight":0
					},
					{
						"config":{
							"layers":[
								{
									"html":"",
									"layerIndex":"0",
									"layerName":"房屋",
									"layerUrl":"/oms/arcgisrest/HA/FW/MapServer/0",
									"link":{
										"tip":"",
										"url":""
									},
									"queryFields":{
										"fields":[
											{
												"alias":"隶属宗地",
												"name":"LSZD",
												"operator":"like",
												"type":"STRING"
											},
											{
												"alias":"自然幢号",
												"name":"ZRZH",
												"operator":"like",
												"type":"STRING"
											}
										],
										"prefix":"%"
									},
									"returnFields":[{
										"alias":"座落地址",
										"name":"ZLDZ",
										"type":"STRING"
									}],
									"serviceId":"015de3dbd93f4028b2425de38ad30165",
									"titleField":{
										"alias":"房屋名称",
										"name":"FWMC"
									},
									"type":"field"
								},
								{
									"html":"",
									"layerIndex":"0",
									"layerName":"宗海",
									"layerUrl":"/oms/arcgisrest/HA/ZH/MapServer/0",
									"link":{
										"tip":"",
										"url":""
									},
									"queryFields":{
										"fields":[{
											"alias":"宗海代码",
											"name":"ZHDM",
											"operator":"like",
											"type":"STRING"
										}],
										"prefix":"%"
									},
									"returnFields":[
										{
											"alias":"项目名称",
											"name":"XMMC",
											"type":"STRING"
										},
										{
											"alias":"海岛用途",
											"name":"HDYT",
											"type":"STRING"
										}
									],
									"serviceId":"015de3dc220b4028b2425de38ad301c5",
									"titleField":{
										"alias":"宗海代码",
										"name":"ZHDM"
									},
									"type":"field"
								},
								{
									"html":"",
									"layerIndex":"0",
									"layerName":"宗地",
									"layerUrl":"/oms/arcgisrest/HA/ZD/MapServer/0",
									"link":{
										"tip":"",
										"url":""
									},
									"queryFields":{
										"fields":[{
											"alias":"地籍号",
											"name":"DJH",
											"operator":"like",
											"type":"STRING"
										}],
										"prefix":"%"
									},
									"returnFields":[{
										"alias":"土地座落",
										"name":"TDZL",
										"type":"STRING"
									}],
									"serviceId":"015de3dbfffc4028b2425de38ad30189",
									"titleField":{
										"alias":"地籍号",
										"name":"DJH"
									},
									"type":"field"
								},
								{
									"html":"",
									"layerIndex":"0",
									"layerName":"地籍子区",
									"layerUrl":"/oms/arcgisrest/HA/DJZQ/MapServer/0",
									"link":{
										"tip":"",
										"url":""
									},
									"queryFields":{
										"fields":[{
											"alias":"地籍子区编号",
											"name":"DJZQBH",
											"operator":"like",
											"type":"STRING"
										}],
										"prefix":"%"
									},
									"returnFields":[
										{
											"alias":"地籍子区名称",
											"name":"DJZQMC",
											"type":"STRING"
										},
										{
											"alias":"所属区域",
											"name":"SSQY",
											"type":"STRING"
										}
									],
									"serviceId":"015de3dbb9414028b2425de38ad3014e",
									"titleField":{
										"alias":"地籍子区名称",
										"name":"DJZQMC"
									},
									"type":"field"
								}
							],
							"merge":false
						},
						"desc":"",
						"display":true,
						"group":"364A0361-2801-4DFE-A125-95E46E93D240",
						"icon":"fa fa-search",
						"id":"9DE8926E-5CFC-4C83-AF77-35D623D0C85F",
						"label":"信息查询",
						"open":false,
						"url":"Query",
						"weight":2
					}
				]
			}
		]
	},
	"widgets":[
		{
			"config":{
				"style":"normal"
			},
			"display":true,
			"id":"MenuBar",
			"open":false,
			"url":"MenuBar",
			"weight":0
		},
		{
			"display":true,
			"id":"Navigation",
			"open":false,
			"url":"Navigation",
			"weight":0
		},
		{
			"config":{
				"style":"default"
			},
			"display":true,
			"open":true,
			"url":"Scalebar",
			"weight":0
		},
		{
			"display":true,
			"id":"Region",
			"open":false,
			"url":"Region",
			"weight":0
		},
		{
			"config":{
				"layers":[{
					"layerAlias":"",
					"layerName":"",
					"returnFields":[],
					"scale":"",
					"serviceId":""
				}],
				"showInfo":false,
				"showResult":false,
				"videoSwitch":false
			},
			"display":true,
			"icon":"fa-location",
			"id":"Location",
			"label":"定位",
			"open":false,
			"url":"Location",
			"weight":0
		}
	]
}